include:
  - compose/pg.docker-compose.yaml
  - compose/minio.docker-compose.yaml
  - compose/qdrant.docker-compose.yaml
  - compose/mlflow.docker-compose.yaml # Requires: minio + pg
  - compose/argilla.docker-compose.yaml # Argilla is still fairly new.
