CREATE DATABASE mlflowdb;
GRANT ALL PRIVILEGES ON DATABASE mlflowdb TO postgres;
CREATE DATABASE labelstudio;
GRANT ALL PRIVILEGES ON DATABASE mlflowdb TO postgres;
CREATE DATABASE langfuse;
GRANT ALL PRIVILEGES ON DATABASE langfuse TO postgres;
