services:
  mlflow:
    container_name: mlflow
    restart: always
    image: ghcr.io/mlflow/mlflow:latest
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      minio:
        condition: service_healthy
        restart: true
    environment:
      - GUNICORN_THREADS=1
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
    ports:
      - "5001:5001"
    command: >
      bash -c "pip install psycopg2-binary && 
      mlflow server 
      --artifacts-destination s3://mlflow 
      --backend-store-uri postgresql://postgres:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/mlflowdb 
      --workers 1 --port 5001 --host 0.0.0.0"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 400M
        reservations:
          cpus: "0.025"
          memory: 50M
