services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=postgres
    volumes:
      - ./pg:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 75M
        reservations:
          cpus: "0.01"
          memory: 6M

volumes:
  postgres:
