
services:
  prefect:
    container_name: prefect
    image: prefecthq/prefect:3.0.0rc13-python3.12
    ports:
      - "4200:4200"
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/prefect
      - PREFECT_API_DATABASE_ECHO=False
      - PREFECT_API_DATABASE_MIGRATE_ON_START=True
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 300M
        reservations:
          cpus: "0.1"
          memory: 50M
