services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant:/qdrant
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1000m
        reservations:
          cpus: "0.5"
          memory: 1000m

volumes:
  qdrant:
